#!/bin/sh

# Move to the git repository root
REPO_ROOT=$(git rev-parse --show-toplevel)
cd "$REPO_ROOT"

# Stash non-staged changes to avoid linting them
git stash push -q --keep-index

# Run golangci-lint on all staged Go files
echo "Running golangci-lint on staged Go files..."
STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')
if [ -n "$STAGED_GO_FILES" ]; then
  # Use xargs to run golangci-lint on each file
  echo "$STAGED_GO_FILES" | xargs golangci-lint run
  if [ $? != 0 ]; then
    echo "golangci-lint found issues. Aborting commit."
    # Restore stashed changes
    git stash pop -q
    exit 1
  fi
fi

# Restore stashed changes
git stash pop -q

exit 0

