on:
  push:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{ github.ref }}-writecache
  cancel-in-progress: true
name: Write Cache
jobs:
  write-cache:
    name: Write Cache
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: just build
      - id: find-go-build-cache
        shell: bash
        run: echo "cache=$(go env GOCACHE)" >> $GITHUB_OUTPUT
      - uses: actions/cache/save@v4
        with:
          path: |
            ~/go/pkg/mod
            ${{ steps.find-go-build-cache.outputs.cache }}
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
